# Generated by Django 2.1.4 on 2019-01-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_point', models.FloatField()),
                ('y_point', models.FloatField()),
            ],
        ),
    ]
